language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn flow:install
script:
  - yarn lint
  - yarn flow
deploy:
  provider: script
  script:
    - yarn now:deploy
  on:
    branch: master
