language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run flow:install
script:
  - yarn run lint
  - yarn run flow
deploy:
  provider: script
  script:
    - npm install -g now
    - yarn run build
    - cd build
    - now -t $NOW_TOKEN -n akronb-yard
  on:
    branch: master
