language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run flow:install
script:
  - yarn run lint
  - yarn run flow
deploy:
  provider: script
  script:
    - yarn run build
  on:
    branch: master
